name: FaithCenter
favicon: null
layout_spectrum: 0.26406
typography_spectrum: 0.87298
title: 'Cultivating Authentic Faith, Hope and Love'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb0000'
    - '#615d5d'
    - '#250404'
    - '#f99998'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
