name: FaithCenter
favicon: null
layout_spectrum: 0.26406
typography_spectrum: 0.87298
title: New Life in Christ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aa282d'
    - '#e4c2c2'
    - '#5f5558'
    - '#271b1b'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
