name: FaithCenter
favicon: null
layout_spectrum: 0.7364
typography_spectrum: 0.29299
title: 'Love, Faith and Hope in Christ'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb0000'
    - '#615d5d'
    - '#250404'
    - '#f99998'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
