name: FaithCenter
favicon: null
layout_spectrum: 0.52378
typography_spectrum: 0.29299
title: 'Cultivating Authentic Faith, Hope and Love'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fb0000'
    - '#615d5d'
    - '#250404'
    - '#f99998'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
